# Generated by Django 5.0.3 on 2024-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='notes',
            name='publish_year',
            field=models.DateField(),
        ),
    ]
