# Generated by Django 5.0.3 on 2024-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notes_author_notes_file_notes_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='title',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='year',
            new_name='desription',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='file',
        ),
    ]
