# Generated by Django 5.0.3 on 2024-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_create_notes_created_rename_place_notes_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='place',
            new_name='Titile',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='publish_year',
        ),
        migrations.AddField(
            model_name='notes',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
