# Generated by Django 5.0.3 on 2024-04-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_place_notes_titile_remove_notes_publish_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='genre',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
