# Generated by Django 5.0.3 on 2024-04-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_notes_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Titile',
            new_name='Title',
        ),
    ]
